### ISSUE TITLE
Add a command to invite team member to the account

### ISSUE THREAD

**Issue by flowck** [dobermanndotdev/dobermann#117]
Inviting a person to a team consists of:

- Sending to them an email with an invitation link that must be valid for a limited time window;
- Upon clicking on the link, person is redirected to a form where she will be able to create an account;
- The the invitation link is invalidated once the account is created or when `time.now() > invitiationLinkExpiryDate`

## Other things to have in consideration
- An email address cannot belong to multiple accounts 
- Members can be invited in bulk
- The invitations should be limited to the available seats each account has got.

## Todo

- [x] Add the API definition of the endpoint to bulk invite members to the team;
- [x] Add the API definition and http port of the endpoint to add a new member;
- [ ] Update the domain, if necessary;
- [ ] Update the repository and tests;
- [ ] Add a command to bulk-invite people by email address;
- [ ] Add a command to create the user of a new member from the invitation token / link;
- [ ] Add a method to the email sender adapter;
- [ ] Component tests;
